[tool.poetry]
name = "transformer"
version = "0.1.0"
description = ""
authors = ["Abdelrhman Nile <abdelrhmannile@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
torch = "^2.2.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
